# 4-1，张量的结构操作

张量的操作主要包括张量的结构操作和张量的数学运算。

张量结构操作诸如：张量创建，索引切片，维度变换，合并分割。

张量数学运算主要有：标量运算，向量运算，矩阵运算。另外我们会介绍张量运算的广播机制。

本篇我们介绍张量的结构操作。

## 一、创建张量

张量创建的许多方法和numpy中创建array的方法很像。

In [4]:
import tensorflow as tf
import numpy as np

In [5]:
a = tf.constant([1,2,3],dtype=tf.float32)
print(a)
tf.print(a)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
[1 2 3]


In [6]:
b = tf.range(10,1,delta=-2)
tf.print(b)

[10 8 6 4 2]


In [8]:
c = tf.linspace(10,0,6)
tf.print(c)

[10 8 6 4 2 0]


In [14]:
d = tf.zeros([3,3])
tf.print(d)
tf.print(d[0])

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[0 0 0]


In [12]:
a = tf.ones([3,3])
b = tf.zeros_like(a,dtype=tf.float32)
tf.print(a)
tf.print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
b = tf.fill([3,2],5)
tf.print(b)

[[5 5]
 [5 5]
 [5 5]]


In [25]:
# 均匀分布随机
# tf.random.set_seed(1) # 设置随机种子
a = tf.random.uniform([5,5],minval=0,maxval=10)
tf.print(a)
print(a.shape)

[[3.32600474 6.45835161 6.99905777 2.62959361 5.51486492]
 [6.71703339 0.214263201 1.72008634 0.739969 7.9267621]
 [8.48169422 7.78671646 6.29696751 8.3506546 2.947855]
 [4.23601627 6.81895733 1.99285746 8.06989861 8.87176418]
 [8.76599121 1.81831121 5.02958059 0.234712362 1.4948988]]
(5, 5)


In [30]:
# 正太随机分布
b = tf.random.normal(a.shape,mean=0,stddev=1)
tf.print(b)

[[-1.87371 0.274597406 -0.0364042595 -0.506392241 -0.201665327]
 [-0.777061701 1.72137773 -0.121972382 0.741182566 1.04614925]
 [-0.0727615356 1.26759028 0.957027435 1.30794752 1.70221901]
 [0.559168518 -0.483352512 0.168694586 0.32278493 0.332817]
 [0.0186989419 -0.448576629 0.667761385 -1.54900885 1.26717639]]


In [31]:
#正态分布随机，剔除2倍方差以外数据重新生成
c = tf.random.truncated_normal(a.shape,mean=0,stddev=1)
tf.print(c)

[[-0.834074318 -1.02077544 -0.63425678 0.515412748 0.865244269]
 [1.16046584 -1.42690039 -0.833565116 -1.58683121 -0.215022638]
 [-0.955602407 -0.054117579 0.683828652 -0.467878103 0.208319575]
 [-0.0726841092 0.866283357 -0.350806683 -1.69972456 1.74361813]
 [0.630323589 0.23178412 0.450689584 -0.312031507 1.43233383]]


In [34]:
# 特殊矩阵
I = tf.eye(4,4)
tf.print(I)

N = tf.linalg.diag([1,2,3,4])
tf.print(N)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## 二、索引切片

张量的索引切片方式和numpy几乎是一样的。切片时支持缺省参数和省略号。

对于tf.Variable,可以通过索引和切片对部分元素进行修改。

对于提取张量的连续子区域，也可以使用tf.slice.

此外，对于不规则的切片提取,可以使用tf.gather,tf.gather_nd,tf.boolean_mask。

tf.boolean_mask功能最为强大，它可以实现tf.gather,tf.gather_nd的功能，并且tf.boolean_mask还可以实现布尔索引。

如果要通过修改张量的某些元素得到新的张量，可以使用tf.where，tf.scatter_nd。

In [39]:
tf.random.set_seed(3)
t = tf.random.uniform([5,5],minval=0,maxval=10,dtype=tf.int32)
tf.print(t)

[[4 7 4 2 9]
 [9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]
 [3 7 0 0 3]]


In [40]:
tf.print(t[0])
tf.print(t[-1])
tf.print(t[:,0])
tf.print(t[:,-1])

[4 7 4 2 9]
[3 7 0 0 3]
[4 9 7 9 3]
[9 7 0 2 3]


In [41]:
tf.print(t[1:4,:])
tf.print(tf.slice(t,[1,0],[3,5])) # 切片，data，start，end

[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]
[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]


In [45]:
#第1行至最后一行，第0列到最后一列每隔两列取一列
tf.print(t[1:4,:4:2])
tf.print(t[1:4:2,:4:2])

[[9 2]
 [7 7]
 [9 9]]
[[9 2]
 [9 9]]


In [48]:
#对变量来说，还可以使用索引和切片修改部分元素
x = tf.Variable([[1,2],[3,4]])
tf.print(x)
x[1,:].assign(tf.constant([0,0]))
tf.print(x)

[[1 2]
 [3 4]]
[[1 2]
 [0 0]]


In [49]:
a = tf.random.uniform([2,2,2],minval=0,maxval=10,dtype=tf.int32)
tf.print(a)

[[[7 3]
  [9 9]]

 [[0 7]
  [9 6]]]


In [50]:
#省略号可以表示多个冒号
tf.print(a[...,1])
tf.print(a[:,:,1])

[[3 9]
 [7 6]]
[[3 9]
 [7 6]]


以上切片方式相对规则，对于不规则的切片提取,可以使用tf.gather,tf.gather_nd,tf.boolean_mask。

考虑班级成绩册的例子，有4个班级，每个班级10个学生，每个学生7门科目成绩。可以用一个4×10×7的张量来表示。

In [51]:
scores = tf.random.uniform((4,10,7),minval=0,maxval=100,dtype=tf.int32)
tf.print(scores)

[[[52 82 66 ... 17 86 14]
  [8 36 94 ... 13 78 41]
  [77 53 51 ... 22 91 56]
  ...
  [11 19 26 ... 89 86 68]
  [60 72 0 ... 11 26 15]
  [24 99 38 ... 97 44 74]]

 [[79 73 73 ... 35 3 81]
  [83 36 31 ... 75 38 85]
  [54 26 67 ... 60 68 98]
  ...
  [20 5 18 ... 32 45 3]
  [72 52 81 ... 88 41 20]
  [0 21 89 ... 53 10 90]]

 [[52 80 22 ... 29 25 60]
  [78 71 54 ... 43 98 81]
  [21 66 53 ... 97 75 77]
  ...
  [6 74 3 ... 53 65 43]
  [98 36 72 ... 33 36 81]
  [61 78 70 ... 7 59 21]]

 [[56 57 45 ... 23 15 3]
  [35 8 82 ... 11 59 97]
  [44 6 99 ... 81 60 27]
  ...
  [76 26 35 ... 51 8 17]
  [33 52 53 ... 78 37 31]
  [71 27 44 ... 0 52 16]]]


In [52]:
#抽取每个班级第0个学生，第5个学生，第9个学生的全部成绩
p = tf.gather(scores,[0,5,9],axis=1)
tf.print(p) # (4,3,7)

[[[52 82 66 ... 17 86 14]
  [24 80 70 ... 72 63 96]
  [24 99 38 ... 97 44 74]]

 [[79 73 73 ... 35 3 81]
  [46 10 94 ... 23 18 92]
  [0 21 89 ... 53 10 90]]

 [[52 80 22 ... 29 25 60]
  [19 12 23 ... 87 86 25]
  [61 78 70 ... 7 59 21]]

 [[56 57 45 ... 23 15 3]
  [6 41 79 ... 97 43 13]
  [71 27 44 ... 0 52 16]]]


In [54]:
#抽取每个班级第0个学生，第5个学生，第9个学生的第1门课程，第3门课程，第6门课程成绩
q = tf.gather(tf.gather(scores,[0,5,9],axis=1),[1,3,6],axis=2)
tf.print(q) #(4,3,3)

[[[82 55 14]
  [80 46 96]
  [99 58 74]]

 [[73 48 81]
  [10 38 92]
  [21 86 90]]

 [[80 57 60]
  [12 34 25]
  [78 71 21]]

 [[57 75 3]
  [41 47 13]
  [27 96 16]]]


In [57]:
# 抽取第0个班级第0个学生，第2个班级的第4个学生，第3个班级的第6个学生的全部成绩
#indices的长度为采样样本的个数，每个元素为采样位置的坐标
s = tf.gather_nd(scores,indices = [(0,0),(2,4),(3,6)])
tf.print(s) # (3,7)

[[52 82 66 ... 17 86 14]
 [99 94 46 ... 1 63 41]
 [46 83 70 ... 90 85 17]]


以上tf.gather和tf.gather_nd的功能也可以用tf.boolean_mask来实现。

In [58]:
#抽取每个班级第0个学生，第5个学生，第9个学生的全部成绩
p = tf.boolean_mask(scores,[True,False,False,False,False,
                            True,False,False,False,True],axis=1)
tf.print(p)

[[[52 82 66 ... 17 86 14]
  [24 80 70 ... 72 63 96]
  [24 99 38 ... 97 44 74]]

 [[79 73 73 ... 35 3 81]
  [46 10 94 ... 23 18 92]
  [0 21 89 ... 53 10 90]]

 [[52 80 22 ... 29 25 60]
  [19 12 23 ... 87 86 25]
  [61 78 70 ... 7 59 21]]

 [[56 57 45 ... 23 15 3]
  [6 41 79 ... 97 43 13]
  [71 27 44 ... 0 52 16]]]


In [59]:
#抽取第0个班级第0个学生，第2个班级的第4个学生，第3个班级的第6个学生的全部成绩
s = tf.boolean_mask(scores,
    [[True,False,False,False,False,False,False,False,False,False],
     [False,False,False,False,False,False,False,False,False,False],
     [False,False,False,False,True,False,False,False,False,False],
     [False,False,False,False,False,False,True,False,False,False]])
tf.print(s)

[[52 82 66 ... 17 86 14]
 [99 94 46 ... 1 63 41]
 [46 83 70 ... 90 85 17]]


In [60]:
#利用tf.boolean_mask可以实现布尔索引

#找到矩阵中小于0的元素
c = tf.constant([[-1,1,-1],[2,2,-2],[3,-3,3]],dtype=tf.float32)
tf.print(c,"\n")



[[-1 1 -1]
 [2 2 -2]
 [3 -3 3]] 



In [61]:
c<0

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True, False,  True],
       [False, False,  True],
       [False,  True, False]])>

In [63]:
tf.print(tf.boolean_mask(c,c<0))
tf.print(c[c<0]) #布尔索引，为boolean_mask的语法糖形式

[-1 -1 -2 -3]
[-1 -1 -2 -3]


以上这些方法仅能提取张量的部分元素值，但不能更改张量的部分元素值得到新的张量。

如果要通过修改张量的部分元素值得到新的张量，可以使用tf.where和tf.scatter_nd。

tf.where可以理解为if的张量版本，此外它还可以用于找到满足条件的所有元素的位置坐标。

tf.scatter_nd的作用和tf.gather_nd有些相反，tf.gather_nd用于收集张量的给定位置的元素，

而tf.scatter_nd可以将某些值插入到一个给定shape的全0的张量的指定位置处

In [65]:
#找到张量中小于0的元素,将其换成np.nan得到新的张量
#tf.where和np.where作用类似，可以理解为if的张量版本
c = tf.constant([[-1,1,-1],[2,2,-2],[3,-3,3]],dtype=tf.float32)
tf.print(c)
tf.fill(c.shape,np.nan)

[[-1 1 -1]
 [2 2 -2]
 [3 -3 3]]


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]], dtype=float32)>

In [67]:
d = tf.where(c<0,tf.fill(c.shape,np.nan),c)# 参数(condition, x=None, y=None, name=None)
tf.print(d)

[[nan 1 nan]
 [2 2 nan]
 [3 nan 3]]


In [68]:
#如果where只有一个参数，将返回所有满足条件的位置坐标
indices = tf.where(c<0) 
indices # 有4个数据是小于0 的，每个数的位置是个列表

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 2],
       [1, 2],
       [2, 1]])>

In [ ]:
# scatter_nd的使用方法
indices = tf.constant([[4], [3], [1], [7]]) # 下标
updates = tf.constant([9, 10, 11, 12])
shape = tf.constant([8])
scatter = tf.scatter_nd(indices, updates, shape)
print(scatter)

In [72]:
#将张量的第[0,0]和[2,1]两个位置元素替换为0得到新的张量
d = c - tf.scatter_nd([[0,0],[2,1]],[c[0,0],c[2,1]],c.shape)
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.,  1., -1.],
       [ 2.,  2., -2.],
       [ 3.,  0.,  3.]], dtype=float32)>

In [73]:
#scatter_nd的作用和gather_nd有些相反
#可以将某些值插入到一个给定shape的全0的张量的指定位置处。
indices = tf.where(c<0)
tf.scatter_nd(indices,tf.gather_nd(c,indices),c.shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.,  0., -1.],
       [ 0.,  0., -2.],
       [ 0., -3.,  0.]], dtype=float32)>

## 三、维度变换

维度变换相关函数主要有 tf.reshape, tf.squeeze, tf.expand_dims, tf.transpose.

tf.reshape 可以改变张量的形状。

tf.squeeze 可以减少维度。

tf.expand_dims 可以增加维度。

tf.transpose 可以交换维度。

tf.reshape可以改变张量的形状，但是其本质上不会改变张量元素的存储顺序，所以，该操作实际上非常迅速，并且是可逆的。

In [75]:
a = tf.random.uniform(shape=[1,3,3,2],
                      minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)
tf.print(a)

TensorShape([1, 3, 3, 2])
[[[[100 44]
   [181 14]
   [90 53]]

  [[205 141]
   [14 24]
   [239 46]]

  [[225 174]
   [212 78]
   [14 144]]]]


In [76]:
# 改成 （3,6）形状的张量
b = tf.reshape(a,[3,6])
tf.print(b.shape)
tf.print(b)

TensorShape([3, 6])
[[100 44 181 14 90 53]
 [205 141 14 24 239 46]
 [225 174 212 78 14 144]]


In [77]:
# 改回成 [1,3,3,2] 形状的张量
c = tf.reshape(b,[1,3,3,2])
tf.print(c)

[[[[100 44]
   [181 14]
   [90 53]]

  [[205 141]
   [14 24]
   [239 46]]

  [[225 174]
   [212 78]
   [14 144]]]]


如果张量在某个维度上只有一个元素，利用tf.squeeze可以消除这个维度。

和tf.reshape相似，它本质上不会改变张量元素的存储顺序。

张量的各个元素在内存中是线性存储的，其一般规律是，同一层级中的相邻元素的物理地址也相邻

In [78]:
s = tf.squeeze(a)
tf.print(s.shape)
tf.print(s)

TensorShape([3, 3, 2])
[[[100 44]
  [181 14]
  [90 53]]

 [[205 141]
  [14 24]
  [239 46]]

 [[225 174]
  [212 78]
  [14 144]]]


In [79]:
d = tf.expand_dims(s,axis=0) #在第0维插入长度为1的一个维度
d

<tf.Tensor: shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[100,  44],
         [181,  14],
         [ 90,  53]],

        [[205, 141],
         [ 14,  24],
         [239,  46]],

        [[225, 174],
         [212,  78],
         [ 14, 144]]]], dtype=int32)>

In [80]:
d = tf.expand_dims(s,axis=0) #在第0维插入长度为1的一个维度
d

<tf.Tensor: shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[100,  44],
         [181,  14],
         [ 90,  53]],

        [[205, 141],
         [ 14,  24],
         [239,  46]],

        [[225, 174],
         [212,  78],
         [ 14, 144]]]], dtype=int32)>

tf.transpose可以交换张量的维度，与tf.reshape不同，它会改变张量元素的存储顺序。

tf.transpose常用于图片存储格式的变换上。

In [81]:
# Batch,Height,Width,Channel
a = tf.random.uniform(shape=[100,600,600,4],minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)

# 转换成 Channel,Height,Width,Batch
s= tf.transpose(a,perm=[3,1,2,0])
tf.print(s.shape)

TensorShape([100, 600, 600, 4])
TensorShape([4, 600, 600, 100])


## 四、合并分割

和numpy类似，可以用tf.concat和tf.stack方法对多个张量进行合并，可以用tf.split方法把一个张量分割成多个张量。

tf.concat和tf.stack有略微的区别，tf.concat是连接，不会增加维度，而tf.stack是堆叠，会增加维度。

In [82]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

tf.concat([a,b,c],axis = 0)

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

In [83]:
tf.concat([a,b,c],axis = 1)

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 1.,  2.,  5.,  6.,  9., 10.],
       [ 3.,  4.,  7.,  8., 11., 12.]], dtype=float32)>

In [87]:
# tf.concat([a,b,c],axis = 2)

In [84]:
tf.stack([a,b,c])

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)>

In [85]:
tf.stack([a,b,c],axis=1)

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]],

       [[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]], dtype=float32)>

In [88]:
tf.stack([a,b,c],axis=2)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 1.,  5.,  9.],
        [ 2.,  6., 10.]],

       [[ 3.,  7., 11.],
        [ 4.,  8., 12.]]], dtype=float32)>

In [90]:
# tf.stack([a,b,c],axis=3)

In [91]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

c = tf.concat([a,b,c],axis = 0)
c

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

In [92]:
#tf.split(value,num_or_size_splits,axis)
tf.split(c,3,axis = 0)  #指定分割份数，平均分割

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[5., 6.],
        [7., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 10.],
        [11., 12.]], dtype=float32)>]

In [93]:
tf.split(c,[2,2,2],axis = 0) #指定每份的记录数量

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[5., 6.],
        [7., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 10.],
        [11., 12.]], dtype=float32)>]